---
# tasks file for backend
- debug:
    msg: "Deploy {{ env }}-{{ service_name }}"

- name: show all the hosts matching the pattern, i.e. all but the group www
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_inventory_hostnames:
    - web_db

- name: Create user every minute
  ansible.builtin.cron:
    name: "create user"
    job: "curl -X 'POST' 'http://{{ item }}:8099/users' -H 'accept: */*' -H 'Content-Type: application/json' -d '{ \"nickname\": \"newNickName\", \"email\": \"email$gmail.com\", \"rating\": 100500 }'"
  with_inventory_hostnames:
    - web_db
